project_id = "ggmyzbijxgnrupucpadp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation_enabled = true

[auth]
enabled = true
port = 54328

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54329

[analytics]
enabled = false
port = 54330
vector_port = 54331
backend = "postgres"